# Uncomment the next line to define a global platform for your project
  platform :ios, '14.1'

target 'iOSSampleApp' do

  use_frameworks!

  pod 'CustomLibrary', :path => '/Users/cassia.barbosa/Documents/Repositories/kmpMonoRepo/CustomLibrary/shared/CustomLibrary.podspec'

  target 'iOSSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSampleAppUITests' do
    # Pods for testing
  end

end
