# Uncomment the next line to define a global platform for your project
  platform :ios, '14.1'

target 'iOSSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CustomLibrary', :path => '/Users/cassia.barbosa/Documents/Repositories/kmpMonoRepo/CustomLibrary/shared/build/cocoapods/publish/debug' 

  target 'iOSSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSampleAppUITests' do
    # Pods for testing
  end

end
