# Uncomment the next line to define a global platform for your project

platform :ios, '14.0'

target 'iOSSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'DegreesLibrary', :git => 'https://github.com/cassiaabarbosa/degreesLibrary.git'

  target 'iOSSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSampleAppUITests' do
    # Pods for testing
  end

end
